package ir.behnamapps.fascratch.inappbilling.domain

import java.net.URI
import java.util.UUID

data class Course(val id: String, val title: String, val description: String, val sku: String,
    val instructor: String = "", val difficulty: Int = 0, val durationSeconds: Double = 0.0,
    val coverUrl: String? = null, val confirmedPurchases: Int? = null, val serverPriceToman: Long? = null,
    val compareAtToman: Long? = null, val discountEndsAtMillis: Long? = null, val difficultyLabel: String = "")
data class Lesson(val id: String, val courseId: String, val section: String, val title: String,
    val version: Int, val bytes: Long, val sha256: String, val difficulty: Int = 0,
    val durationSeconds: Double = 0.0, val coverUrl: String? = null, val description: String = "",
    val isPreview: Boolean = false, val previewUrl: String? = null, val difficultyLabel: String = "")

/** Numeric identities remain stable; older APIs/caches still have readable badges. */
object DifficultyLevel {
    private val defaults = listOf("مقدماتی", "آسان", "متوسط", "پیشرفته", "حرفه‌ای",
        "چالش‌برانگیز", "دشوار", "بسیار دشوار", "تخصصی", "فوق‌تخصصی")
    private val emojis = listOf("🌱", "🙂", "💡", "🚀", "🔥", "🎯", "🧩", "⚡", "🏆", "💎")
    fun label(level: Int, custom: String = ""): String {
        if (level !in 1..10) return ""
        val title = custom.trim()
        return title.takeIf { it.codePointCount(0, it.length) in 1..40 && it != "null" && it.none { c -> c.isISOControl() || c == '<' || c == '>' } }
            ?: defaults[level - 1]
    }
    fun emoji(level: Int): String = emojis.getOrNull(level - 1).orEmpty()
}

// Do not use data classes for receipts/credentials: autogenerated toString must never leak secrets.
class Receipt(val sku: String, val token: String)
class CourseAccess(val courseId: String, val token: String, val expiresAtMillis: Long)
class CourseFailure(val userMessage: String, val status: Int = 0, val code: String = "") : Exception(userMessage)

interface BillingGateway {
    val provider: String
    suspend fun owned(sku: String): Receipt?
    suspend fun purchase(sku: String): Receipt
    fun close()
}

interface PurchaseBackend {
    suspend fun verify(course: Course, provider: String, receipt: Receipt, restore: Boolean): CourseAccess
}

interface ReceiptStore {
    fun saveReceipt(courseId: String, receipt: Receipt)
    fun receipt(courseId: String): Receipt?
    fun saveAccess(access: CourseAccess)
}

/** A failed inventory query must NEVER be interpreted as "not owned" and trigger a new purchase. */
class BuyCourse(private val backend: PurchaseBackend, private val receipts: ReceiptStore) {
    suspend fun execute(course: Course, billing: BillingGateway, restoreOnly: Boolean): CourseAccess {
        val previous = billing.owned(course.sku)
        val receipt = previous ?: if (restoreOnly) {
            throw CourseFailure("خرید قبلی این دوره در حساب فعلی استور پیدا نشد.", code = "not_owned")
        } else billing.purchase(course.sku)
        if (receipt.sku != course.sku || receipt.token.isBlank()) throw CourseFailure("رسید خرید با دوره مطابقت ندارد.")
        // Persist before HTTP verification: process death/outage must not lose the paid receipt.
        receipts.saveReceipt(course.id, receipt)
        val access = backend.verify(course, billing.provider, receipt, previous != null || restoreOnly)
        if (access.courseId != course.id) throw CourseFailure("دسترسی برگشتی با دوره مطابقت ندارد.")
        receipts.saveAccess(access)
        return access
    }
}

object CoursePolicy {
    fun discountVisible(course: Course, now: Long): Boolean = course.serverPriceToman != null &&
        course.compareAtToman != null && course.compareAtToman > course.serverPriceToman &&
        (course.discountEndsAtMillis == null || now < course.discountEndsAtMillis)
    fun serverPrice(sku: String, priceSku: String?, amount: Any?): Long? {
        if (priceSku == null) return null
        require(priceSku == sku)
        if (amount == null) return null
        val value = when (amount) { is Long -> amount; is Int -> amount.toLong(); else -> throw IllegalArgumentException("Invalid server price") }
        require(value in 0..1_000_000_000_000L)
        return value
    }
    fun purchaseNetworkAvailable(internet: Boolean, validated: Boolean) = internet && validated
    fun canLearn(lesson: Lesson, purchased: Boolean) = lesson.isPreview || purchased
    fun previewUrl(base: String, lesson: Lesson): String {
        require(lesson.isPreview)
        val url = requireNotNull(lesson.previewUrl)
        require(sameOrigin(base, url))
        val target = URI(url)
        val prefix = URI(base.trimEnd('/')).path + "/lessons/${uuid(lesson.id)}/video/"
        require(target.fragment == null && target.path.startsWith(prefix))
        uuid(target.path.removePrefix(prefix))
        require(!target.rawQuery.isNullOrBlank())
        return url
    }
    fun revokesAccess(code: String) = code in setOf("refunded", "rejected", "not_owned", "access_disabled")
    fun uuid(value: String): String {
        require(UUID.fromString(value).toString().equals(value, ignoreCase = true))
        return value.lowercase()
    }
    fun downloadKey(lesson: Lesson): String {
        require(lesson.version >= 0 && lesson.bytes in 1..(1024L * 1024 * 1024))
        require(lesson.sha256.matches(Regex("[a-fA-F0-9]{64}")))
        return "${uuid(lesson.id)}-${lesson.version}-${lesson.sha256.lowercase()}.mp4"
    }
    fun sameOrigin(base: String, candidate: String): Boolean = runCatching {
        val a = URI(base)
        val b = URI(candidate)
        b.scheme == "https" && a.host == b.host && b.userInfo == null && (b.port == -1 || b.port == 443)
    }.getOrDefault(false)
}
